apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

  - name: ClickHouse
    type: clickhouse
    access: proxy
    url: http://clickhouse:8123
    isDefault: false
    editable: true
    jsonData:
      defaultDatabase: analytics
      tlsSkipVerify: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true

  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: famgo
    user: famgo
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      tlsMode: disable
